# Generated by Django 4.1.9 on 2023-05-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadasemana',
            name='entrada1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diadasemana',
            name='saida1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
